{
    "data": {
        "@version": "3.0",
        "@time": "2024-07-19 08:49:13",
        "@type": "post",
        "@filename": "b000000017.xml",
        "open_time": "0000-00-00",
        "close_time": "0000-00-00",
        "lang_name": "Big5",
        "board_id": "1001305431",
        "node": "000000017",
        "site": "1000110001",
        "pt": "2023-10-03 00:13:41",
        "poster": "11120411",
        "realname": "陳瀚傑",
        "email": "jackc0410@gmail.com",
        "homepage": null,
        "subject": "108. 若遞迴到某層就異常終止，要如何強制它繼續執行到下一層？",
        "content": "<p>在遞迴函數中使用 try-catch。當異常發生時，在 catch 塊中決定如何處理異常情況後繼續遞迴。</p>\r\n\r\n<p>例如在funtion(int x)中設置一個try，裡面放條件判斷式，如果判斷式成立就throw error 給 catch 然後繼續遞迴。像是funtion(x+1)</p>",
        "attach": null,
        "rcount": null,
        "rank": null,
        "hit": "25",
        "lang": "1"
    }
}